import numpy as np

a=np.array([1,2,3])
b=np.zeros((2,2))
print(a,b)
print(np.arange(10))
print(np.zeros(7))
print("---------------------------")
print("eye\n",np.eye(6))
print(np.array([1,1,0,0],dtype=bool))
print("---------------------------")
arr=np.random.rand(25)
print(arr)
print("---------------------------")
ar=np.array([1,2,3])
print(arr.reshape(5,5))
print("---------------------------")
print(ar+ar)
print(ar-ar)
print(ar/ar)
print(ar*ar)
print("---------------------------")
print(np.sqrt(ar))
print(np.sum(ar))
print(np.sin(ar))
print(np.cos(ar))
print(np.log(ar))
print(np.exp(ar))
print("---------------------------")
x=np.array([[1,2],[3,4]])
y=np.array([[4,5],[6,7]])
print(x.dot(y),"\n----------------------")
print(np.dot(x,y),"\n--------------------")

